### ISSUE TITLE
new syntax

### ISSUE THREAD

**Issue by xiaoouwang** [ZenMule/MiaoZhang-PraatScripts#1]
Hi,

I think you can write the scripts with new syntax, see below:

(Old syntax) Create Sound as pure tone... tone 1 0 0.4 44100 440 0.2 0.01 0.01
(intermediate syntax) "Create Sound as pure tone...", "tone", 1, 0, 0.4, 44100, 440, 0.2, 0.01, 0.01
(new syntax) Create Sound as pure tone: "tone", 1, 0, 0.4, 44100, 440, 0.2, 0.01, 0.01

personally I find it easier to parse for human eyes 🤒 
also I often use comma rather than tab to segment columns, again it's a personal preference

Keep up the great job!

**Comment by ZenMule** [comment]
Hi,

Thanks for the comment!

Yeah, I totally agree.
When I learned the new syntax the first time, I was like "how the hell they didn't come up with the new way in the first place?"
